name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            - run: npm ci
            - run: npm test --if-present
            - run: npm run build

            - name: Deploy to live
              if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
              run: npx playpass deploy
              env:
                  PLAYPASS_TOKEN: ${{ secrets.PLAYPASS_TOKEN }}

            - name: Deploy to branch preview
              if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
              run: npx playpass deploy --prefix "${GITHUB_REF/refs\/heads\/}"
              env:
                  PLAYPASS_TOKEN: ${{ secrets.PLAYPASS_TOKEN }}
