#!/usr/bin/env python3

import os
import tempfile
from subprocess import run, check_call

sdk_dir = os.getcwd()
project_dir = os.path.join(tempfile.mkdtemp(), "project")

pack = run(["npm", "pack"], capture_output=True, check=True)
tarball = os.path.join(sdk_dir, pack.stdout.decode().rstrip())
print(tarball)

def playpass (args, **kwargs):
    check_call(["node", os.path.join(sdk_dir, "dist", "cjs", "cli", "index.js")] + args, **kwargs)

def npm (args, **kwargs):
    check_call(["npm"] + args, **kwargs)

playpass(["create", project_dir, "--local", "--template", "https://github.com/playpassgames/playpass-game-template"])
npm(["install", tarball], cwd=project_dir)
playpass(["help"], cwd=project_dir)
npm(["run", "build"], cwd=project_dir)
# playpass(["deploy"], cwd=project_dir)
