site_dir: dist/docs

site_name: Playpass SDK

nav:
    - Quickstart: index.md
    # - Integration: integration.md
    - Create Your First Game:
        # - Start a New Project: create.md
        - Add a Share Button: share.md
        - Store Player Data: storage.md
        - Add a Login Button: account.md
        - Show Highscore Leaderboards: leaderboards.md
        - Add Multiplayer with Groups: groups.md
        # - Receive Payments: payments.md
        - Deploy Your Game: deploy.md
        - Managing Your Game: managing.md
    - API Reference:
        - playpass: api/index.md
        - playpass.account: api/modules/account.md
        - playpass.device: api/modules/device.md
        - playpass.groups: api/modules/groups.md
        - playpass.leaderboards: api/modules/leaderboards.md
    - Changelog: changelog.md
        # - playpass.payments: api/modules/payments.md
        # - Analytics: analytics.md
        # - Feature Flags: feature-flags.md
        # - Groups: groups.md
        # - Hosting: hosting.md
        # - Sharing: sharing.md
        # - Storage: storage.md

markdown_extensions:
    - toc:
        toc_depth: 3
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

extra:
    generator: false

theme:
    name: "material"
    palette:
        primary: orange
        accent: deep orange
    features:
        - navigation.sections
        - toc.integrate
