name: CI

on: [push, pull_request]

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  registry-url: 'https://npm.pkg.github.com/'
                  scope: '@play-co'
                  cache: 'npm'

            - run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PLAYCO_PACKAGES_TOKEN }}
            - run: npm run build
            - run: npm test

            - name: CLI sanity check
              run: |
                  playpass="./dist/cjs/cli/index.js"
                  $playpass help
                  # $playpass create /tmp/test-playpass-create --template daily-level

            - name: Build kitchen-sink
              run: |
                  npm ci
                  npm run build
                  npm test --if-present
              working-directory: test/kitchen-sink

            - name: Build templates
              run: |
                  for package in templates/*/package.json; do
                      cd `dirname "$package"`
                      npm ci
                      npm run build
                      npm test --if-present
                      cd -
                  done

            - name: Build docs
              run: |
                  pip install mkdocs-material
                  npm run docs

            - name: Deploy kitchen-sink to https://kitchen-sink.playpass.games
              if: github.ref == 'refs/heads/main'
              run: |
                  playpass="../../dist/cjs/cli/index.js"
                  $playpass deploy
              working-directory: test/kitchen-sink
              env:
                  PLAYPASS_TOKEN: ${{ secrets.PLAYPASS_TOKEN }}

            - name: Deploy templates to https://<TEMPLATE>--template.playpass.games
              if: github.ref == 'refs/heads/main'
              run: |
                  playpass="../../dist/cjs/cli/index.js"
                  for package in templates/*/package.json; do
                      cd `dirname "$package"`
                      $playpass deploy --prefix `basename $PWD`
                      cd -
                  done
              env:
                  PLAYPASS_TOKEN: ${{ secrets.PLAYPASS_TOKEN }}

            - name: Deploy docs
              if: github.ref == 'refs/heads/main'
              run: |
                  pip install awscli
                  aws s3 sync dist/docs/ s3://playco-sdk-documentation/ --delete
                  aws cloudfront create-invalidation --distribution-id E2EGL7UEW6JUEO --paths '/*'
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}

    verifyCLI:
        strategy:
            matrix:
                os: [macos-latest, windows-latest]
        name: CLI check
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  registry-url: 'https://npm.pkg.github.com/'
                  scope: '@play-co'
                  cache: 'npm'

            - run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PLAYCO_PACKAGES_TOKEN }}
            - run: npm run build
            - run: npm test

            - name: CLI sanity check
              run: |
                  node ./dist/cjs/cli/index.js help
                  cd templates/daily-level/
                  npm i
                  npm run build
                  node ./../../dist/cjs/cli/index.js deploy
              env:
                  PLAYPASS_TOKEN: ${{ secrets.PLAYPASS_TOKEN }}